# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_mysql:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout
          5s --health-retries 5
        ports:
        - 3306:3306
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 2.6.9
          gemfile: Gemfile.rails.5.2-stable
        - ruby: 3.0.3
          gemfile: Gemfile.rails.6.1-stable
        - ruby: 3.1.1
          gemfile: Gemfile.rails.7.0-stable
    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
      DB: mysql
    steps:
    - uses: actions/checkout@v2
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true
    - name: Setup database
      run: |
        mysql -e 'create database IF NOT EXISTS test;' -u root --password=password -P 3306 -h 127.0.0.1
    - name: Run tests
      run: bundle exec rspec
  test_pg:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          DB: postgresql
        options: "--health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5"
        ports:
        - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 2.6.9
          gemfile: Gemfile.rails-5.2-stable
        - ruby: 2.6.9
          gemfile: Gemfile.rails-6.1-stable
        - ruby: 2.7.5
          gemfile: Gemfile.rails-6.1-stable
        - ruby: 2.7.5
          gemfile: Gemfile.rails-7.0-stable
        - ruby: 3.0.3
          gemfile: Gemfile.rails-6.1-stable
        - ruby: 3.1.1
          gemfile: Gemfile.rails-7.0-stable
    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
      DB: postgresql
    steps:
    - uses: actions/checkout@v2
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true
    - name: Setup database
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client
        PGPASSWORD=postgres psql -c 'create database test;' -U postgres -p 5432 -h localhost
    - name: Run tests
      run: bundle exec rspec
  test_sqlite:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 2.6.9
          gemfile: Gemfile.rails-5.2-stable
    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
      DB: sqlite
    steps:
    - uses: actions/checkout@v2
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true
    - name: Run tests
      run: bundle exec rspec



# jobs:
#   test:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         ruby-version: ['2.6', '2.7', '3.0']

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Ruby
#       uses: ruby/setup-ruby@1
#       with:
#         ruby-version: ${{ matrix.ruby-version }}
#         bundler-cache: true # runs 'bundle install' and caches installed gems automatically
#     - name: Run tests
#       run: bundle exec rake